[package]
name = "maple"
build = "build.rs"
edition = "2021"
version = "0.1.41"
rust-version = "1.65"
license = "MIT"
publish = false
include = ["/Cargo.toml", "src/*.rs"]
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
homepage = "https://g